import { Zap, Mic, Wand2, Type, AudioLines, History, User, Globe } from 'lucide-react';

export type Tab = 'tts' | 'stt' | 'clean' | 'changer' | 'clone' | 'translate' | 'profile' | 'history';
export type Tier = 'FREE' | 'BASIC' | 'PREMIUM' | 'PRO';

export interface Voice {
  id: string;
  name: string;
  gender: 'Male' | 'Female' | 'Neutral';
  country: string;
  language: string;
  languageCode: string;
  tone: string;
  gradient: string;
}

export const VOICES: Voice[] = [
  { id: 'ara', name: 'Ara', gender: 'Female', country: 'Global', language: 'Multilingual', languageCode: 'multilingual', tone: 'Natural', gradient: 'from-pink-500 via-rose-400 to-orange-400' },
  { id: 'eve', name: 'Eve', gender: 'Female', country: 'Global', language: 'Multilingual', languageCode: 'multilingual', tone: 'Natural', gradient: 'from-fuchsia-500 via-purple-500 to-indigo-500' },
  { id: 'leo', name: 'Leo', gender: 'Male', country: 'Global', language: 'Multilingual', languageCode: 'multilingual', tone: 'Natural', gradient: 'from-cyan-500 via-blue-500 to-indigo-600' },
  { id: 'rex', name: 'Rex', gender: 'Male', country: 'Global', language: 'Multilingual', languageCode: 'multilingual', tone: 'Natural', gradient: 'from-emerald-400 via-teal-500 to-cyan-600' },
  { id: 'sal', name: 'Sal', gender: 'Male', country: 'Global', language: 'Multilingual', languageCode: 'multilingual', tone: 'Natural', gradient: 'from-orange-500 via-red-500 to-rose-600' },
  { id: 'jpi39icg', name: 'Jian', gender: 'Male', country: 'China', language: 'Chinese (Simplified)', languageCode: 'zh-CN', tone: 'Young', gradient: 'from-blue-600 via-indigo-500 to-violet-600' },
  { id: 'd18jlf6v', name: 'Hao', gender: 'Male', country: 'China', language: 'Chinese (Simplified)', languageCode: 'zh-CN', tone: 'Young', gradient: 'from-rose-400 via-pink-400 to-fuchsia-500' },
  { id: 'oao30dn1', name: 'Yue', gender: 'Female', country: 'China', language: 'Chinese (Simplified)', languageCode: 'zh-CN', tone: 'Natural', gradient: 'from-slate-500 via-blue-500 to-cyan-400' },
  { id: '33g9t0jl', name: 'Xia', gender: 'Female', country: 'China', language: 'Chinese (Simplified)', languageCode: 'zh-CN', tone: 'Middle-aged', gradient: 'from-amber-400 via-yellow-400 to-lime-400' },
  { id: '26w6ihxi', name: 'Pavel', gender: 'Male', country: 'Russia', language: 'Russian', languageCode: 'ru-RU', tone: 'Middle-aged', gradient: 'from-green-500 via-emerald-500 to-teal-500' },
  { id: 'dr8gqysu', name: 'Andrei', gender: 'Male', country: 'Russia', language: 'Russian', languageCode: 'ru-RU', tone: 'Middle-aged', gradient: 'from-red-600 via-rose-500 to-pink-500' },
  { id: 'wy0m9l5w', name: 'Dmitri', gender: 'Male', country: 'Russia', language: 'Russian', languageCode: 'ru-RU', tone: 'Middle-aged', gradient: 'from-pink-400 via-rose-300 to-red-400' },
  { id: 'om17cury', name: 'Irina', gender: 'Female', country: 'Russia', language: 'Russian', languageCode: 'ru-RU', tone: 'Young', gradient: 'from-red-500 via-orange-400 to-amber-400' },
  { id: 'x7avnu1k', name: 'Enzo', gender: 'Male', country: 'Italy', language: 'Italian', languageCode: 'it-IT', tone: 'Young', gradient: 'from-fuchsia-400 via-pink-400 to-rose-500' },
  { id: 'bcs7l2c3', name: 'Matteo', gender: 'Male', country: 'Italy', language: 'Italian', languageCode: 'it-IT', tone: 'Young', gradient: 'from-pink-300 via-rose-400 to-fuchsia-400' },
  { id: 'hqxr4yub', name: 'Luca', gender: 'Male', country: 'Italy', language: 'Italian', languageCode: 'it-IT', tone: 'Middle-aged', gradient: 'from-sky-500 via-blue-500 to-indigo-500' },
  { id: 'h27ltdnz', name: 'Alessandro', gender: 'Male', country: 'Italy', language: 'Italian', languageCode: 'it-IT', tone: 'Young', gradient: 'from-violet-400 via-purple-400 to-fuchsia-500' },
  { id: 'uupejnl3', name: 'Vikram', gender: 'Male', country: 'India', language: 'Hindi', languageCode: 'hi-IN', tone: 'Young', gradient: 'from-blue-400 via-sky-400 to-cyan-400' },
  { id: '89q2pnko', name: 'Karan', gender: 'Male', country: 'India', language: 'Hindi', languageCode: 'hi-IN', tone: 'Young', gradient: 'from-indigo-500 via-blue-500 to-sky-500' },
  { id: '6visocna', name: 'Arjun', gender: 'Male', country: 'India', language: 'Hindi', languageCode: 'hi-IN', tone: 'Young', gradient: 'from-red-500 via-orange-500 to-yellow-500' },
  { id: '73xd5dum', name: 'Ananya', gender: 'Female', country: 'India', language: 'Hindi', languageCode: 'hi-IN', tone: 'Young', gradient: 'from-amber-600 via-red-500 to-rose-600' },
  { id: '0p0rt7o1', name: 'Remi', gender: 'Male', country: 'France', language: 'French', languageCode: 'fr-FR', tone: 'Young', gradient: 'from-blue-500 via-indigo-400 to-violet-500' },
  { id: 'hbxkrnwm', name: 'Hugo', gender: 'Male', country: 'France', language: 'French', languageCode: 'fr-FR', tone: 'Young', gradient: 'from-blue-600 via-blue-500 to-cyan-500' },
  { id: '4v3o4p0r', name: 'Antoine', gender: 'Male', country: 'France', language: 'French', languageCode: 'fr-FR', tone: 'Old', gradient: 'from-amber-500 via-yellow-400 to-lime-400' },
  { id: '69smp8rm', name: 'Camille', gender: 'Female', country: 'France', language: 'French', languageCode: 'fr-FR', tone: 'Middle-aged', gradient: 'from-zinc-500 via-gray-400 to-slate-500' },
  { id: 'yis75yfp', name: 'Manuel', gender: 'Male', country: 'Spain', language: 'Spanish', languageCode: 'es-ES', tone: 'Old', gradient: 'from-green-500 via-emerald-400 to-teal-400' },
  { id: 'ekhwx401', name: 'Javier', gender: 'Male', country: 'Spain', language: 'Spanish', languageCode: 'es-ES', tone: 'Middle-aged', gradient: 'from-yellow-500 via-amber-400 to-orange-500' },
  { id: 'jupvcf34', name: 'Diego', gender: 'Male', country: 'Spain', language: 'Spanish', languageCode: 'es-ES', tone: 'Natural', gradient: 'from-orange-500 via-amber-400 to-yellow-400' },
  { id: '0hhfxxqq', name: 'Andres', gender: 'Male', country: 'Spain', language: 'Spanish', languageCode: 'es-ES', tone: 'Middle-aged', gradient: 'from-green-600 via-emerald-500 to-cyan-500' },
  { id: '0ih5oi34', name: 'Kasper', gender: 'Male', country: 'Denmark', language: 'Danish', languageCode: 'da-DK', tone: 'Young', gradient: 'from-red-500 via-rose-400 to-pink-400' },
  { id: 'gwnexu6y', name: 'Lars', gender: 'Male', country: 'Denmark', language: 'Danish', languageCode: 'da-DK', tone: 'Middle-aged', gradient: 'from-yellow-500 via-amber-500 to-red-500' },
  { id: 'q5n046zm', name: 'Sigrid', gender: 'Female', country: 'Denmark', language: 'Danish', languageCode: 'da-DK', tone: 'Young', gradient: 'from-red-600 via-red-500 to-rose-500' },
  { id: '97zmdc6s', name: 'Ida', gender: 'Female', country: 'Denmark', language: 'Danish', languageCode: 'da-DK', tone: 'Middle-aged', gradient: 'from-blue-700 via-blue-600 to-indigo-600' },
  { id: 'fc7de6afcf6c', name: 'Duc', gender: 'Male', country: 'Vietnam', language: 'Vietnamese', languageCode: 'vi-VN', tone: 'Young', gradient: 'from-emerald-500 via-green-400 to-teal-400' },
  { id: 'fbf753daafd4', name: 'Fah', gender: 'Female', country: 'Thailand', language: 'Thai', languageCode: 'th-TH', tone: 'Young', gradient: 'from-amber-600 via-orange-500 to-red-500' },
  { id: 'f8cf5c2c78d4', name: 'Grace', gender: 'Female', country: 'United States', language: 'English', languageCode: 'en-US', tone: 'Young', gradient: 'from-green-500 via-teal-400 to-cyan-400' },
  { id: 'e22152e06fd8', name: 'Axel', gender: 'Male', country: 'Sweden', language: 'Swedish', languageCode: 'sv-SE', tone: 'Middle-aged', gradient: 'from-red-500 via-orange-400 to-amber-400' },
  { id: 'dfe7b9e7d217', name: 'Valtteri', gender: 'Male', country: 'Finland', language: 'Finnish', languageCode: 'fi-FI', tone: 'Natural', gradient: 'from-pink-500 via-rose-400 to-orange-400' },
  { id: 'd634b6da3d3b', name: 'Aylin', gender: 'Female', country: 'Turkey', language: 'Turkish', languageCode: 'tr-TR', tone: 'Old', gradient: 'from-fuchsia-500 via-purple-500 to-indigo-500' },
  { id: 'd0cb9ff07d95', name: 'Sakura', gender: 'Female', country: 'Japan', language: 'Japanese', languageCode: 'ja-JP', tone: 'Middle-aged', gradient: 'from-cyan-500 via-blue-500 to-indigo-600' },
  { id: 'c3a2c594479e', name: 'Helmi', gender: 'Female', country: 'Finland', language: 'Finnish', languageCode: 'fi-FI', tone: 'Young', gradient: 'from-emerald-400 via-teal-500 to-cyan-600' },
  { id: 'bf9fe5b5f981', name: 'Jun-seo', gender: 'Male', country: 'South Korea', language: 'Korean', languageCode: 'ko-KR', tone: 'Natural', gradient: 'from-orange-500 via-red-500 to-rose-600' },
  { id: 'b5ae17439907', name: 'Min-jun', gender: 'Male', country: 'South Korea', language: 'Korean', languageCode: 'ko-KR', tone: 'Middle-aged', gradient: 'from-blue-600 via-indigo-500 to-violet-600' },
  { id: 'b1a7441b97a1', name: 'Ren', gender: 'Male', country: 'Japan', language: 'Japanese', languageCode: 'ja-JP', tone: 'Young', gradient: 'from-rose-400 via-pink-400 to-fuchsia-500' },
  { id: 'abfbdf26f115', name: 'Mateus', gender: 'Male', country: 'Brazil', language: 'Portuguese', languageCode: 'pt-BR', tone: 'Middle-aged', gradient: 'from-slate-500 via-blue-500 to-cyan-400' },
  { id: 'a13662ba951c', name: 'Thijs', gender: 'Male', country: 'Netherlands', language: 'Dutch', languageCode: 'nl-NL', tone: 'Middle-aged', gradient: 'from-amber-400 via-yellow-400 to-lime-400' },
  { id: 'a0401c9101f8', name: 'Seo-yeon', gender: 'Female', country: 'South Korea', language: 'Korean', languageCode: 'ko-KR', tone: 'Young', gradient: 'from-green-500 via-emerald-500 to-teal-500' },
  { id: '99c95cc8a177', name: 'Haruto', gender: 'Male', country: 'Japan', language: 'Japanese', languageCode: 'ja-JP', tone: 'Young', gradient: 'from-red-600 via-rose-500 to-pink-500' },
  { id: '97fabd54445f', name: 'Katarzyna', gender: 'Female', country: 'Poland', language: 'Polish', languageCode: 'pl-PL', tone: 'Middle-aged', gradient: 'from-pink-400 via-rose-300 to-red-400' },
  { id: '96819d0bd28d', name: 'Daniel', gender: 'Male', country: 'United States', language: 'English', languageCode: 'en-US', tone: 'Middle-aged', gradient: 'from-red-500 via-orange-400 to-amber-400' },
  { id: '91a9ffcaaab5', name: 'Hana', gender: 'Female', country: 'Japan', language: 'Japanese', languageCode: 'ja-JP', tone: 'Young', gradient: 'from-fuchsia-400 via-pink-400 to-rose-500' },
  { id: '908c4626660f', name: 'Krit', gender: 'Male', country: 'Thailand', language: 'Thai', languageCode: 'th-TH', tone: 'Young', gradient: 'from-pink-300 via-rose-400 to-fuchsia-400' },
  { id: '8a8b3d7dc1e8', name: 'Nadia', gender: 'Female', country: 'Saudi Arabia', language: 'Arabic', languageCode: 'ar-SA', tone: 'Young', gradient: 'from-sky-500 via-blue-500 to-indigo-500' },
  { id: '83c6f4fea98e', name: 'Eero', gender: 'Male', country: 'Finland', language: 'Finnish', languageCode: 'fi-FI', tone: 'Natural', gradient: 'from-violet-400 via-purple-400 to-fuchsia-500' },
  { id: '7a9ee820b342', name: 'Minh', gender: 'Male', country: 'Vietnam', language: 'Vietnamese', languageCode: 'vi-VN', tone: 'Natural', gradient: 'from-blue-400 via-sky-400 to-cyan-400' },
  { id: '79f3a8b96d43', name: 'Claire', gender: 'Female', country: 'United States', language: 'English', languageCode: 'en-US', tone: 'Middle-aged', gradient: 'from-indigo-500 via-blue-500 to-sky-500' },
  { id: '78a495fdbb39', name: 'James', gender: 'Male', country: 'United States', language: 'English', languageCode: 'en-US', tone: 'Young', gradient: 'from-red-500 via-orange-500 to-yellow-500' },
  { id: '70013edeb8e8', name: 'Khalid', gender: 'Male', country: 'Saudi Arabia', language: 'Arabic', languageCode: 'ar-SA', tone: 'Young', gradient: 'from-amber-600 via-red-500 to-rose-600' },
  { id: '6da5baee46d0', name: 'Beatriz', gender: 'Female', country: 'Brazil', language: 'Portuguese', languageCode: 'pt-BR', tone: 'Middle-aged', gradient: 'from-blue-500 via-indigo-400 to-violet-500' },
  { id: '670a0c3ac005', name: 'Emre', gender: 'Male', country: 'Turkey', language: 'Turkish', languageCode: 'tr-TR', tone: 'Young', gradient: 'from-blue-600 via-blue-500 to-cyan-500' },
  { id: '5f523eb2b455', name: 'Lan', gender: 'Female', country: 'Vietnam', language: 'Vietnamese', languageCode: 'vi-VN', tone: 'Young', gradient: 'from-amber-500 via-yellow-400 to-lime-400' },
  { id: '58d27475085e', name: 'Femke', gender: 'Female', country: 'Netherlands', language: 'Dutch', languageCode: 'nl-NL', tone: 'Middle-aged', gradient: 'from-zinc-500 via-gray-400 to-slate-500' },
  { id: '4ff93971bfdc', name: 'Aroon', gender: 'Male', country: 'Thailand', language: 'Thai', languageCode: 'th-TH', tone: 'Young', gradient: 'from-green-500 via-emerald-400 to-teal-400' },
  { id: '490ea3be50b1', name: 'Saga', gender: 'Female', country: 'Sweden', language: 'Swedish', languageCode: 'sv-SE', tone: 'Young', gradient: 'from-yellow-500 via-amber-400 to-orange-500' },
  { id: '458705c07139', name: 'Clara', gender: 'Female', country: 'Germany', language: 'German', languageCode: 'de-DE', tone: 'Middle-aged', gradient: 'from-orange-500 via-amber-400 to-yellow-400' },
  { id: '42a9ea5c7190', name: 'Ploy', gender: 'Female', country: 'Thailand', language: 'Thai', languageCode: 'th-TH', tone: 'Middle-aged', gradient: 'from-green-600 via-emerald-500 to-cyan-500' },
  { id: '41321eb41295', name: 'Moritz', gender: 'Male', country: 'Germany', language: 'German', languageCode: 'de-DE', tone: 'Natural', gradient: 'from-red-500 via-rose-400 to-pink-400' },
  { id: '40f31906b23d', name: 'Niklas', gender: 'Male', country: 'Germany', language: 'German', languageCode: 'de-DE', tone: 'Middle-aged', gradient: 'from-yellow-500 via-amber-500 to-red-500' },
  { id: '3d030bc92a87', name: 'Rafael', gender: 'Male', country: 'Brazil', language: 'Portuguese', languageCode: 'pt-BR', tone: 'Middle-aged', gradient: 'from-red-600 via-red-500 to-rose-500' },
  { id: '3a7889066fa2', name: 'Lena', gender: 'Female', country: 'Germany', language: 'German', languageCode: 'de-DE', tone: 'Young', gradient: 'from-blue-700 via-blue-600 to-indigo-600' },
  { id: '37329fd8895a', name: 'Mateusz', gender: 'Male', country: 'Poland', language: 'Polish', languageCode: 'pl-PL', tone: 'Middle-aged', gradient: 'from-emerald-500 via-green-400 to-teal-400' },
  { id: '35c8d7f60dc8', name: 'Layla', gender: 'Female', country: 'Saudi Arabia', language: 'Arabic', languageCode: 'ar-SA', tone: 'Young', gradient: 'from-amber-600 via-orange-500 to-red-500' },
  { id: '34fd4dce1ba3', name: 'Elina', gender: 'Female', country: 'Finland', language: 'Finnish', languageCode: 'fi-FI', tone: 'Middle-aged', gradient: 'from-green-500 via-teal-400 to-cyan-400' },
  { id: '2badb5f46b1e', name: 'Jakub', gender: 'Male', country: 'Poland', language: 'Polish', languageCode: 'pl-PL', tone: 'Young', gradient: 'from-red-500 via-orange-400 to-amber-400' },
  { id: '247783ebdd51', name: 'Noor', gender: 'Female', country: 'Netherlands', language: 'Dutch', languageCode: 'nl-NL', tone: 'Middle-aged', gradient: 'from-pink-500 via-rose-400 to-orange-400' },
  { id: '244e27b39200', name: 'Ruben', gender: 'Male', country: 'Netherlands', language: 'Dutch', languageCode: 'nl-NL', tone: 'Middle-aged', gradient: 'from-fuchsia-500 via-purple-500 to-indigo-500' },
  { id: '23be42535a45', name: 'Ji-yeon', gender: 'Female', country: 'South Korea', language: 'Korean', languageCode: 'ko-KR', tone: 'Young', gradient: 'from-cyan-500 via-blue-500 to-indigo-600' },
  { id: '23468361b4ef', name: 'Tariq', gender: 'Male', country: 'Saudi Arabia', language: 'Arabic', languageCode: 'ar-SA', tone: 'Natural', gradient: 'from-emerald-400 via-teal-500 to-cyan-600' },
  { id: '1f046a033914', name: 'Erik', gender: 'Male', country: 'Sweden', language: 'Swedish', languageCode: 'sv-SE', tone: 'Middle-aged', gradient: 'from-orange-500 via-red-500 to-rose-600' },
  { id: '1b12d5daee6b', name: 'Aleksandra', gender: 'Female', country: 'Poland', language: 'Polish', languageCode: 'pl-PL', tone: 'Young', gradient: 'from-blue-600 via-indigo-500 to-violet-600' },
  { id: '182a91893636', name: 'Kaan', gender: 'Male', country: 'Turkey', language: 'Turkish', languageCode: 'tr-TR', tone: 'Middle-aged', gradient: 'from-rose-400 via-pink-400 to-fuchsia-500' },
  { id: '15985536f5d7', name: 'Isabela', gender: 'Female', country: 'Brazil', language: 'Portuguese', languageCode: 'pt-BR', tone: 'Young', gradient: 'from-slate-500 via-blue-500 to-cyan-400' },
  { id: '159744921aa4', name: 'Linnea', gender: 'Female', country: 'Sweden', language: 'Swedish', languageCode: 'sv-SE', tone: 'Young', gradient: 'from-amber-400 via-yellow-400 to-lime-400' },
  { id: '0895a5b8ce5c', name: 'Mai', gender: 'Female', country: 'Vietnam', language: 'Vietnamese', languageCode: 'vi-VN', tone: 'Young', gradient: 'from-green-500 via-emerald-500 to-teal-500' },
  { id: '081994dd6edc', name: 'Elif', gender: 'Female', country: 'Turkey', language: 'Turkish', languageCode: 'tr-TR', tone: 'Young', gradient: 'from-red-600 via-rose-500 to-pink-500' },
  { id: 'f702f406', name: 'Olli', gender: 'Male', country: 'Finland', language: 'Finnish', languageCode: 'fi-FI', tone: 'Middle-aged', gradient: 'from-pink-400 via-rose-300 to-red-400' },
  { id: 'f4b9d6fc', name: 'Omar', gender: 'Male', country: 'Saudi Arabia', language: 'Arabic', languageCode: 'ar-SA', tone: 'Young', gradient: 'from-red-500 via-orange-400 to-amber-400' },
  { id: 'f331ee80', name: 'Ahmet', gender: 'Male', country: 'Turkey', language: 'Turkish', languageCode: 'tr-TR', tone: 'Middle-aged', gradient: 'from-fuchsia-400 via-pink-400 to-rose-500' },
  { id: 'f2f41225', name: 'Maria', gender: 'Female', country: 'Spain', language: 'Spanish', languageCode: 'es-ES', tone: 'Middle-aged', gradient: 'from-pink-300 via-rose-400 to-fuchsia-400' },
  { id: 'f15c6a6a', name: 'Henry', gender: 'Male', country: 'United Kingdom', language: 'English', languageCode: 'en-GB', tone: 'Middle-aged', gradient: 'from-sky-500 via-blue-500 to-indigo-500' },
  { id: 'ef4ce33e', name: 'Daan', gender: 'Male', country: 'Netherlands', language: 'Dutch', languageCode: 'nl-NL', tone: 'Middle-aged', gradient: 'from-violet-400 via-purple-400 to-fuchsia-500' },
  { id: 'eacafe1e', name: 'Vincent', gender: 'Male', country: 'Belgium', language: 'French', languageCode: 'fr-BE', tone: 'Old', gradient: 'from-blue-400 via-sky-400 to-cyan-400' },
  { id: 'e5da67a7', name: 'Linh', gender: 'Female', country: 'Vietnam', language: 'Vietnamese', languageCode: 'vi-VN', tone: 'Young', gradient: 'from-indigo-500 via-blue-500 to-sky-500' },
  { id: 'e5d4f53e', name: 'Pol', gender: 'Male', country: 'Spain', language: 'Catalan', languageCode: 'ca-ES', tone: 'Middle-aged', gradient: 'from-red-500 via-orange-500 to-yellow-500' },
  { id: 'e521cc67', name: 'Hui', gender: 'Female', country: 'China', language: 'Chinese (Simplified)', languageCode: 'zh-CN', tone: 'Young', gradient: 'from-amber-600 via-red-500 to-rose-600' },
  { id: 'e1fc5a89', name: 'Felix', gender: 'Male', country: 'Germany', language: 'German', languageCode: 'de-DE', tone: 'Middle-aged', gradient: 'from-blue-500 via-indigo-400 to-violet-500' },
  { id: 'e1b1007e', name: 'Rohan', gender: 'Male', country: 'Bangladesh', language: 'Bengali', languageCode: 'bn-BD', tone: 'Young', gradient: 'from-blue-600 via-blue-500 to-cyan-500' },
  { id: 'd74461c6', name: 'Hyun-woo', gender: 'Male', country: 'South Korea', language: 'Korean', languageCode: 'ko-KR', tone: 'Middle-aged', gradient: 'from-amber-500 via-yellow-400 to-lime-400' },
  { id: 'd2313a0d', name: 'Pablo', gender: 'Male', country: 'Spain', language: 'Spanish', languageCode: 'es-ES', tone: 'Young', gradient: 'from-zinc-500 via-gray-400 to-slate-500' },
  { id: 'd11249e6', name: 'Emma', gender: 'Female', country: 'United States', language: 'English', languageCode: 'en-US', tone: 'Old', gradient: 'from-green-500 via-emerald-400 to-teal-400' },
  { id: 'cfccf16b', name: 'Mads', gender: 'Male', country: 'Denmark', language: 'Danish', languageCode: 'da-DK', tone: 'Young', gradient: 'from-yellow-500 via-amber-400 to-orange-500' },
  { id: 'ce19f825', name: 'Magdalena', gender: 'Female', country: 'Poland', language: 'Polish', languageCode: 'pl-PL', tone: 'Young', gradient: 'from-orange-500 via-amber-400 to-yellow-400' },
  { id: 'cdb1cec8', name: 'Lieke', gender: 'Female', country: 'Netherlands', language: 'Dutch', languageCode: 'nl-NL', tone: 'Old', gradient: 'from-green-600 via-emerald-500 to-cyan-500' },
  { id: 'c630b236', name: 'Jordi', gender: 'Male', country: 'Spain', language: 'Catalan', languageCode: 'ca-ES', tone: 'Old', gradient: 'from-red-500 via-rose-400 to-pink-400' },
  { id: 'c3cdb7a4', name: 'Bram', gender: 'Male', country: 'Belgium', language: 'Dutch', languageCode: 'nl-BE', tone: 'Young', gradient: 'from-yellow-500 via-amber-500 to-red-500' },
  { id: 'bedd6226', name: 'Olivia', gender: 'Female', country: 'United Kingdom', language: 'English', languageCode: 'en-GB', tone: 'Young', gradient: 'from-red-600 via-red-500 to-rose-500' },
  { id: 'bcf738e4', name: 'Vihaan', gender: 'Male', country: 'India', language: 'Hindi', languageCode: 'hi-IN', tone: 'Young', gradient: 'from-blue-700 via-blue-600 to-indigo-600' },
  { id: 'bab9c92f', name: 'Elsa', gender: 'Female', country: 'Sweden', language: 'Swedish', languageCode: 'sv-SE', tone: 'Middle-aged', gradient: 'from-emerald-500 via-green-400 to-teal-400' },
  { id: 'aedba6b4', name: 'Jeroen', gender: 'Male', country: 'Belgium', language: 'Dutch', languageCode: 'nl-BE', tone: 'Middle-aged', gradient: 'from-amber-600 via-orange-500 to-red-500' },
  { id: 'a7b78b05', name: 'Sean', gender: 'Male', country: 'Ireland', language: 'English', languageCode: 'en-IE', tone: 'Middle-aged', gradient: 'from-green-500 via-teal-400 to-cyan-400' },
  { id: 'a69bdfe7', name: 'Astrid', gender: 'Female', country: 'Denmark', language: 'Danish', languageCode: 'da-DK', tone: 'Young', gradient: 'from-red-500 via-orange-400 to-amber-400' },
  { id: 'a656d78f', name: 'Budi', gender: 'Male', country: 'Indonesia', language: 'Indonesian', languageCode: 'id-ID', tone: 'Middle-aged', gradient: 'from-pink-500 via-rose-400 to-orange-400' },
  { id: 'a5341c30', name: 'Nicha', gender: 'Female', country: 'Thailand', language: 'Thai', languageCode: 'th-TH', tone: 'Young', gradient: 'from-fuchsia-500 via-purple-500 to-indigo-500' },
  { id: 'a2aa4b79', name: 'Pooja', gender: 'Female', country: 'Bangladesh', language: 'Bengali', languageCode: 'bn-BD', tone: 'Natural', gradient: 'from-cyan-500 via-blue-500 to-indigo-600' },
  { id: 'a24f5341', name: 'Mikhail', gender: 'Male', country: 'Russia', language: 'Russian', languageCode: 'ru-RU', tone: 'Young', gradient: 'from-emerald-400 via-teal-500 to-cyan-600' },
  { id: 'a0fa45a6', name: 'Pedro', gender: 'Male', country: 'Brazil', language: 'Portuguese', languageCode: 'pt-BR', tone: 'Middle-aged', gradient: 'from-orange-500 via-red-500 to-rose-600' },
  { id: 'a00ce99a', name: 'Priya', gender: 'Female', country: 'India', language: 'Hindi', languageCode: 'hi-IN', tone: 'Middle-aged', gradient: 'from-blue-600 via-indigo-500 to-violet-600' },
  { id: '9efdd836', name: 'Istvan', gender: 'Male', country: 'Hungary', language: 'Hungarian', languageCode: 'hu-HU', tone: 'Young', gradient: 'from-rose-400 via-pink-400 to-fuchsia-500' },
  { id: '9ec6157c', name: 'Aino', gender: 'Female', country: 'Finland', language: 'Finnish', languageCode: 'fi-FI', tone: 'Young', gradient: 'from-slate-500 via-blue-500 to-cyan-400' },
  { id: '9ab26871', name: 'Wei', gender: 'Male', country: 'China', language: 'Chinese (Simplified)', languageCode: 'zh-CN', tone: 'Young', gradient: 'from-amber-400 via-yellow-400 to-lime-400' },
  { id: '93bea908', name: 'William', gender: 'Male', country: 'Sweden', language: 'Swedish', languageCode: 'sv-SE', tone: 'Young', gradient: 'from-green-500 via-emerald-500 to-teal-500' },
  { id: '7f989258', name: 'Adi', gender: 'Male', country: 'Indonesia', language: 'Indonesian', languageCode: 'id-ID', tone: 'Young', gradient: 'from-red-600 via-rose-500 to-pink-500' },
  { id: '777d3f85', name: 'Catarina', gender: 'Female', country: 'Brazil', language: 'Portuguese', languageCode: 'pt-BR', tone: 'Middle-aged', gradient: 'from-pink-400 via-rose-300 to-red-400' },
  { id: '7160ae2c', name: 'Krisztina', gender: 'Female', country: 'Hungary', language: 'Hungarian', languageCode: 'hu-HU', tone: 'Middle-aged', gradient: 'from-red-500 via-orange-400 to-amber-400' },
  { id: '70071d42', name: 'Tomasz', gender: 'Male', country: 'Poland', language: 'Polish', languageCode: 'pl-PL', tone: 'Middle-aged', gradient: 'from-fuchsia-400 via-pink-400 to-rose-500' },
  { id: '6fe32f8a', name: 'Sophie', gender: 'Female', country: 'Netherlands', language: 'Dutch', languageCode: 'nl-NL', tone: 'Middle-aged', gradient: 'from-pink-300 via-rose-400 to-fuchsia-400' },
  { id: '6a41d324', name: 'Liam', gender: 'Male', country: 'United States', language: 'English', languageCode: 'en-US', tone: 'Middle-aged', gradient: 'from-sky-500 via-blue-500 to-indigo-500' },
  { id: '6997b0ec', name: 'Yang', gender: 'Male', country: 'China', language: 'Chinese (Simplified)', languageCode: 'zh-CN', tone: 'Middle-aged', gradient: 'from-violet-400 via-purple-400 to-fuchsia-500' },
  { id: '681cd005', name: 'Gabor', gender: 'Male', country: 'Hungary', language: 'Hungarian', languageCode: 'hu-HU', tone: 'Middle-aged', gradient: 'from-blue-400 via-sky-400 to-cyan-400' },
  { id: '6583fcc2', name: 'Eszter', gender: 'Female', country: 'Hungary', language: 'Hungarian', languageCode: 'hu-HU', tone: 'Young', gradient: 'from-indigo-500 via-blue-500 to-sky-500' },
  { id: '5f0c2251', name: 'Youssef', gender: 'Male', country: 'Saudi Arabia', language: 'Arabic', languageCode: 'ar-SA', tone: 'Young', gradient: 'from-red-500 via-orange-500 to-yellow-500' },
  { id: '5e3e2cbe', name: 'Mikko', gender: 'Male', country: 'Finland', language: 'Finnish', languageCode: 'fi-FI', tone: 'Young', gradient: 'from-amber-600 via-red-500 to-rose-600' },
  { id: '5d695b41', name: 'Marc', gender: 'Male', country: 'South Africa', language: 'English', languageCode: 'en-ZA', tone: 'Middle-aged', gradient: 'from-blue-500 via-indigo-400 to-violet-500' },
  { id: '57b26f54', name: 'Anika', gender: 'Female', country: 'Bangladesh', language: 'Bengali', languageCode: 'bn-BD', tone: 'Young', gradient: 'from-blue-600 via-blue-500 to-cyan-500' },
  { id: '57700f39', name: 'Leon', gender: 'Male', country: 'Italy', language: 'Italian', languageCode: 'it-IT', tone: 'Middle-aged', gradient: 'from-amber-500 via-yellow-400 to-lime-400' },
  { id: '524f4cb1', name: 'Lucas', gender: 'Male', country: 'Denmark', language: 'Danish', languageCode: 'da-DK', tone: 'Young', gradient: 'from-zinc-500 via-gray-400 to-slate-500' },
  { id: '4e1d5545', name: 'Quang', gender: 'Male', country: 'Vietnam', language: 'Vietnamese', languageCode: 'vi-VN', tone: 'Middle-aged', gradient: 'from-green-500 via-emerald-400 to-teal-400' },
  { id: '4d9e4c6f', name: 'Mathieu', gender: 'Male', country: 'Belgium', language: 'French', languageCode: 'fr-BE', tone: 'Young', gradient: 'from-yellow-500 via-amber-400 to-orange-500' },
  { id: '4d3af3e1', name: 'Mireia', gender: 'Female', country: 'Spain', language: 'Catalan', languageCode: 'ca-ES', tone: 'Middle-aged', gradient: 'from-orange-500 via-amber-400 to-yellow-400' },
  { id: '4c7f16ff', name: 'Oscar', gender: 'Male', country: 'Sweden', language: 'Swedish', languageCode: 'sv-SE', tone: 'Young', gradient: 'from-green-600 via-emerald-500 to-cyan-500' },
  { id: '4b7af2d7', name: 'Somchai', gender: 'Male', country: 'Thailand', language: 'Thai', languageCode: 'th-TH', tone: 'Middle-aged', gradient: 'from-red-500 via-rose-400 to-pink-400' },
  { id: '4984accb', name: 'Zofia', gender: 'Female', country: 'Poland', language: 'Polish', languageCode: 'pl-PL', tone: 'Young', gradient: 'from-yellow-500 via-amber-500 to-red-500' },
  { id: '47519c37', name: 'Freja', gender: 'Female', country: 'Denmark', language: 'Danish', languageCode: 'da-DK', tone: 'Middle-aged', gradient: 'from-red-600 via-red-500 to-rose-500' },
  { id: '46a802e3', name: 'Lucia', gender: 'Female', country: 'Spain', language: 'Spanish', languageCode: 'es-ES', tone: 'Young', gradient: 'from-blue-700 via-blue-600 to-indigo-600' },
  { id: '45357fd3', name: 'Mathilde', gender: 'Female', country: 'Belgium', language: 'French', languageCode: 'fr-BE', tone: 'Young', gradient: 'from-emerald-500 via-green-400 to-teal-400' },
  { id: '44c91d64', name: 'Sonja', gender: 'Female', country: 'Germany', language: 'German', languageCode: 'de-DE', tone: 'Middle-aged', gradient: 'from-amber-600 via-orange-500 to-red-500' },
  { id: '43423dee', name: 'Giulia', gender: 'Female', country: 'Italy', language: 'Italian', languageCode: 'it-IT', tone: 'Middle-aged', gradient: 'from-green-500 via-teal-400 to-cyan-400' },
  { id: '3b7f37c9', name: 'Anke', gender: 'Female', country: 'Belgium', language: 'Dutch', languageCode: 'nl-BE', tone: 'Middle-aged', gradient: 'from-red-500 via-orange-400 to-amber-400' },
  { id: '3b312632', name: 'Alice', gender: 'Female', country: 'Sweden', language: 'Swedish', languageCode: 'sv-SE', tone: 'Young', gradient: 'from-pink-500 via-rose-400 to-orange-400' },
  { id: '3a3e080c', name: 'Sofia', gender: 'Female', country: 'Finland', language: 'Finnish', languageCode: 'fi-FI', tone: 'Middle-aged', gradient: 'from-fuchsia-500 via-purple-500 to-indigo-500' },
  { id: '39e46ca3', name: 'Hoang', gender: 'Male', country: 'Vietnam', language: 'Vietnamese', languageCode: 'vi-VN', tone: 'Young', gradient: 'from-cyan-500 via-blue-500 to-indigo-600' },
  { id: '355dca53', name: 'Niamh', gender: 'Female', country: 'Ireland', language: 'English', languageCode: 'en-IE', tone: 'Middle-aged', gradient: 'from-emerald-400 via-teal-500 to-cyan-600' },
  { id: '330f1e6d', name: 'Pim', gender: 'Female', country: 'Thailand', language: 'Thai', languageCode: 'th-TH', tone: 'Young', gradient: 'from-orange-500 via-red-500 to-rose-600' },
  { id: '2902bcfd', name: 'Piotr', gender: 'Male', country: 'Poland', language: 'Polish', languageCode: 'pl-PL', tone: 'Middle-aged', gradient: 'from-blue-600 via-indigo-500 to-violet-600' },
  { id: '20fa3f2e', name: 'Sri', gender: 'Female', country: 'Indonesia', language: 'Indonesian', languageCode: 'id-ID', tone: 'Young', gradient: 'from-rose-400 via-pink-400 to-fuchsia-500' },
  { id: '1ebfec36', name: 'Marco', gender: 'Male', country: 'Italy', language: 'Italian', languageCode: 'it-IT', tone: 'Young', gradient: 'from-slate-500 via-blue-500 to-cyan-400' },
  { id: '1a59f327', name: 'Carlos', gender: 'Male', country: 'Spain', language: 'Spanish', languageCode: 'es-ES', tone: 'Young', gradient: 'from-amber-400 via-yellow-400 to-lime-400' },
  { id: '18245f0d', name: 'Bas', gender: 'Male', country: 'Netherlands', language: 'Dutch', languageCode: 'nl-NL', tone: 'Middle-aged', gradient: 'from-green-500 via-emerald-500 to-teal-500' },
  { id: '155d4e9b', name: 'Nuria', gender: 'Female', country: 'Spain', language: 'Catalan', languageCode: 'ca-ES', tone: 'Middle-aged', gradient: 'from-red-600 via-rose-500 to-pink-500' },
  { id: '135ff7ec', name: 'Thandi', gender: 'Female', country: 'South Africa', language: 'English', languageCode: 'en-ZA', tone: 'Middle-aged', gradient: 'from-pink-400 via-rose-300 to-red-400' },
  { id: '0d3372eb', name: 'Sergei', gender: 'Male', country: 'Russia', language: 'Russian', languageCode: 'ru-RU', tone: 'Young', gradient: 'from-red-500 via-orange-400 to-amber-400' },
  { id: '0b875ae2', name: 'Sonia', gender: 'Female', country: 'Russia', language: 'Russian', languageCode: 'ru-RU', tone: 'Middle-aged', gradient: 'from-fuchsia-400 via-pink-400 to-rose-500' },
  { id: '0b54c30d', name: 'Tanvir', gender: 'Male', country: 'Bangladesh', language: 'Bengali', languageCode: 'bn-BD', tone: 'Young', gradient: 'from-pink-300 via-rose-400 to-fuchsia-400' },
  { id: '09b02491', name: 'Mei', gender: 'Female', country: 'China', language: 'Chinese (Simplified)', languageCode: 'zh-CN', tone: 'Young', gradient: 'from-sky-500 via-blue-500 to-indigo-500' },
  { id: '07e283bf', name: 'Aisyah', gender: 'Female', country: 'Indonesia', language: 'Indonesian', languageCode: 'id-ID', tone: 'Young', gradient: 'from-violet-400 via-purple-400 to-fuchsia-500' },
  { id: '0735ff93', name: 'Diya', gender: 'Female', country: 'India', language: 'Hindi', languageCode: 'hi-IN', tone: 'Young', gradient: 'from-blue-400 via-sky-400 to-cyan-400' },
  { id: '0463086e', name: 'Thanawat', gender: 'Male', country: 'Thailand', language: 'Thai', languageCode: 'th-TH', tone: 'Young', gradient: 'from-indigo-500 via-blue-500 to-sky-500' },
  { id: '025a38c5', name: 'Yasmin', gender: 'Female', country: 'Saudi Arabia', language: 'Arabic', languageCode: 'ar-SA', tone: 'Young', gradient: 'from-red-500 via-orange-500 to-yellow-500' },
  { id: '01a7edae', name: 'Chloe', gender: 'Female', country: 'Belgium', language: 'French', languageCode: 'fr-BE', tone: 'Middle-aged', gradient: 'from-amber-600 via-red-500 to-rose-600' },
];

export const TIER_LIMITS = {
  FREE: { pulse: 20000, maxTTSChars: 5000, maxAudioMins: 5, cloneLimit: 0 },
  BASIC: { pulse: 60000, maxTTSChars: 5000, maxAudioMins: 5, cloneLimit: 2 },
  PREMIUM: { pulse: 150000, maxTTSChars: 10000, maxAudioMins: 10, cloneLimit: 5 },
  PRO: { pulse: 800000, maxTTSChars: 15000, maxAudioMins: 15, cloneLimit: 10 },
} as const;

export const PLANS = [
  { id: 'FREE' as Tier, name: 'Free', priceMonthly: 0, priceYearly: 0, desc: 'Test the engine', features: ['20,000 Pulse/month', '5,000 characters TTS limit', '5 minutes STT/Audio limit', 'No Voice Cloning'], popular: false },
  { id: 'BASIC' as Tier, name: 'Basic', priceMonthly: 5, priceYearly: 50, desc: 'For regular creators', features: ['60,000 Pulse/month', '5,000 characters TTS limit', '5 minutes STT/Audio limit', 'Voice Cloning Access (Max 2)'], popular: true },
  { id: 'PREMIUM' as Tier, name: 'Premium', priceMonthly: 10, priceYearly: 100, desc: 'For serious creators', features: ['150,000 Pulse/month', '10,000 characters TTS limit', '10 minutes STT/Audio limit', 'Voice Cloning Access (Max 5)'], popular: false },
  { id: 'PRO' as Tier, name: 'Pro', priceMonthly: 50, priceYearly: 500, desc: 'High-volume production', features: ['800,000 Pulse/month', '15,000 characters TTS limit', '15 minutes STT/Audio limit', 'Voice Cloning Access (Max 10)'], popular: false },
];

export const TABS = [
  { id: 'tts', label: 'Text to Speech', icon: Wand2, desc: 'Convert text to natural voice' },
  { id: 'stt', label: 'Speech to Text', icon: Type, desc: 'Transcribe file/live conversations' },
  { id: 'translate', label: 'Translation', icon: Globe, desc: 'Translate audio to another language' },
  { id: 'changer', label: 'Voice Changer', icon: AudioLines, desc: 'Transform voice style' },
  { id: 'clone', label: 'Clone Voice', icon: Zap, desc: 'Create a custom voice identity' },
  { id: 'clean', label: 'Audio Cleaner', icon: Mic, desc: 'Remove noise & enhance' },
  { id: 'history', label: 'History', icon: History, desc: 'Your generation records' },
  { id: 'profile', label: 'Profile', icon: User, desc: 'Account & Billing' },
] as const;

export const TRANSLATION_LANGUAGES = [
  { id: 'English', name: 'English', flag: '🇺🇸' },
  { id: 'Spanish', name: 'Spanish', flag: '🇪🇸' },
  { id: 'French', name: 'French', flag: '🇫🇷' },
  { id: 'German', name: 'German', flag: '🇩🇪' },
  { id: 'Italian', name: 'Italian', flag: '🇮🇹' },
  { id: 'Portuguese', name: 'Portuguese', flag: '🇵🇹' },
  { id: 'Japanese', name: 'Japanese', flag: '🇯🇵' },
  { id: 'Korean', name: 'Korean', flag: '🇰🇷' },
  { id: 'Chinese (Simplified)', name: 'Chinese (Simp)', flag: '🇨🇳' },
  { id: 'Russian', name: 'Russian', flag: '🇷🇺' },
  { id: 'Arabic', name: 'Arabic', flag: '🇸🇦' },
  { id: 'Hindi', name: 'Hindi', flag: '🇮🇳' },
  { id: 'Vietnamese', name: 'Vietnamese', flag: '🇻🇳' },
];

export const formatSTTText = (text: string) => {
  if (!text) return '';
  const sentences = text.match(/[^.!?]+[.!?]*/g) || [text];
  const formattedSentences = sentences.map(s => {
    let trimmed = s.trim();
    if (!trimmed) return '';
    trimmed = trimmed.charAt(0).toUpperCase() + trimmed.slice(1);
    if (!/[.!?]$/.test(trimmed)) trimmed += '.';
    return trimmed;
  }).filter(Boolean);

  const paragraphs = [];
  for (let i = 0; i < formattedSentences.length; i += 3) {
    paragraphs.push(formattedSentences.slice(i, i + 3).join(' '));
  }
  return paragraphs.join('\n\n');
};